<div class="well well-small span11">
<h5>LEGAL DISCLAIMER</h5>
At SCHOOLD U, we understand your concerns about the privacy of personal information. Because of this, we have established the following guidelines concerning the collection, use and security of information.
This statement discloses the privacy practices for www.SCHOOLDU.com. When you visit www.SCHOOLDU.com, you can expect to be notified of: what personally identifiable information of yours is collected; what organization is collecting the information; how the information is used; with whom the information may be shared; what choices are available to you regarding collection, use and distribution of the information; what kind of security procedures are in place to protect the loss, misuse or alteration of information under the company's control; and how you can correct any inaccuracies in the information.
USING THIS WEB SITE CONFIRMS YOUR CONSENT AND AGREEMENT TO OUR PRIVACY POLICY, INCLUDING SCHOOLD U'S COLLECTION, USE AND DISCLOSURE OF INFORMATION DESCRIBED HEREIN.
SCHOOLDU is the publisher of the www.SCHOOLDU.com web site. SCHOOLD U has created this privacy statement in order to demonstrate our firm commitment to privacy. The following discloses our information gathering and dissemination practices for this Web Site: www.SCHOOLDU.com
Web Statistics, Cookies & Links
SCHOOLD U uses "session cookies" while a visitor is making a donation. "Cookies" are bits of information that are stored by your browser on your hard drive. We use "session cookies" so that we can properly verify a donor's identity as they move from one donation page to the next. For our nonprofits, we use "session cookies" and "persistent cookies" in addition to verifying personal information, so that we can provide secure access to donor information. These session cookies are not linked to personally identifiable information.
The statistics program on our web server collects aggregate information on what pages consumers' access or visit which we use for internal review and to improve the content of our web site. Like most web site administrators we use log files that record information such as Internet protocol (IP) addresses, browser type, Internet service provider (ISP), referring/exit pages, platform type, date/time stamp, and page navigation. IP addresses that are recorded by our log files are not linked to personally identifiable information. This information is not personal information.
This site may contain links to other sites. We are not responsible for the privacy practices or the content of such Web sites. We encourage our users to be aware when they leave our site and to read the privacy statements of each and every web site that collects personally identifiable information. This privacy statement applies solely to information collected by this web site.
We collect your name and email address when you donate through this Web Site. We will use your name and email address only to communicate with you, and we will not sell, rent or distribute your name or email address to any third party (except the charity you chose). We will not disclose any of your personal information, expect when we believe in good faith that the law requires it, or to protect the rights or property of SCHOOLD U.
<br/><br/>
Security<br/>
Please do not send email to us with personal information. We have no way to secure personal information sent via email because this information can be accessed by other users on the Internet. If you send us email to ask a question, we will only use the information you provide to answer your request. Personal information will not be provided to a non-affiliated third party without your prior consent, except as permitted by federal and state law. If you have submitted information about yourself through our Web site and/or email message and would like for us to delete that information from our records, please send an e-mail to us. We will make every effort to delete your personal information from our files.
Donations through SCHOOLD U will be distributed to the charity you selected and are handled exclusively by a shareholder company that is SCHOOLD U's strategic partner - Snoball. The information that you provide is used only to complete your donation. Your name and contact information will be provided to the charity you supported through SCHOOLD U by way of Snoball. Each charity has its own policies regarding privacy of donor information. Please contact the charity you contribute to directly to learn about their privacy policies. Before you confirm your donation through the SCHOOLD U giving system, you may be asked what information you wish to be shared with the recipient charity(ies). You may have a choice of: full contact information, name and email address only, or no personal information (anonymous). SCHOOLD U respects donor privacy and only shares information with donor consent.  For example, when a donor has asked to remain anonymous, no information is shared with the charity - we simply confirm that a donation has been made.
To provide services to nonprofits, SCHOOLD U collects organizational information such as: organization name, tax identification number, address, email address, contact person, credit card number, etc.  We collect this information so that we can process any fees and to screen organizations for our services. Applicants fill out an online Application Form, which our staff reviews. We may contact an applicant to verify information. The set-up fees and monthly fees are processed through a credit card processing company. This company does not save, share, store or use personally identifiable information for any secondary purposes.
<br/><br/>
Policy Changes<br/>
We reserve the right to change or update this Privacy Policy at any time. Any changes made to our privacy policy will be posted on this site in a manner that is easily identifiable. Please review our privacy policy on a regular basis to review any changes.
You do not need to call or do anything as a result of this notice. It simply informs you of how SCHOOLD U protects your nonpublic personal information.
<br/><br/>
Choice/Opt-Out<br/>
Our site provides users the opportunity to opt-out of receiving communications from us at the point where we request information about the visitor.
This site gives users the following options for removing their email addresses from our database to not receive future EMAIL communications:
You can contact us: support@schooldu.com
<br/><br/>

Correct/Update<br/>
This site gives users the following options for changing and modifying email address information that we can access on our servers or which you have provided us when accepting our Terms and Conditions.
You can contact us: support@schooldu.com
Contacting the Web Site
If you have any questions about this privacy statement, the practices of this site, or your dealings with this Web site, you can contact us: support@schooldu.com.
<br/><br/>
TERMS OF USE<br/>
<br/>
1. User's Acknowledgment and Acceptance of Terms<br/>
SCHOOLD U (referred to as "us" or "we") provides the www.SCHOOLDU.com site and various related services (together referred to as this "site") subject to your compliance with all the terms, conditions, and notices contained or referenced herein (the "Terms of Use"), as well as any other written agreement between us (or your company). In addition, when using particular services or materials on this site, users shall be subject to any posted guidelines or rules applicable to such services or materials that may contain terms and conditions in addition to those in these Terms of Use. All such guidelines or rules are hereby incorporated by reference into these Terms of Use.
BY COMPLETING THE REGISTRATION PROCESS AND/OR USING THIS SITE, YOU AGREE TO BE BOUND BY THESE TERMS OF USE. IF YOU DO NOT WISH TO BE BOUND BY THE THESE TERMS OF USE, PLEASE EXIT THE SITE NOW. YOUR REMEDY FOR DISSATISFACTION WITH THIS SITE, OR ANY PRODUCTS, SERVICES, CONTENT, OR OTHER INFORMATION AVAILABLE ON OR THROUGH THIS SITE, IS TO STOP USING THE SITE AND/OR THOSE PARTICULAR PRODUCTS OR SERVICES. YOUR AGREEMENT WITH US REGARDING COMPLIANCE WITH THESE TERMS OF USE BECOMES EFFECTIVE IMMEDIATELY UPON COMMENCEMENT OF YOUR USE OF THIS SITE.
These Terms of Use are effective as of January 1, 2013. We reserve the right to change these Terms of Use from time to time without notice to you. You acknowledge and agree that it is your responsibility to review this site and these Terms of Use periodically and to be aware of any modifications. Your continued use of this site after such modifications will constitute your acknowledgment of the modified Terms of Use and agreement to abide and be bound by the modified Terms of Use.
As used in these Terms of Use, references to our "Affiliates" include our owners, subsidiaries, affiliated companies, officers, directors, suppliers, partners, sponsors, and advertisers, and includes (without limitation) all parties involved in creating, producing, and/or delivering this site and/or its contents.
<br/><br/>
2. Description of Services<br/>
We make various services available on this site including, but not limited to, rules- based giving to charitable organizations. Fees for the various services are set out in the membership and service fees described elsewhere in this site. You are solely responsible for providing, at your own expense, all equipment necessary to use the services, including a computer and modem; and your own Internet access (including payment of telephone service fees associated with such access). You have the ability to design your own rules for giving on the Site. You are solely responsible for the rules you design or adopt from other users of the site, including any charitable donations incurred. You also understand that once a rule is designed or adopted by you, such rule and the resulting donations will continue until you turn off the rule.
We reserve the sole right to either modify or discontinue the site, including any features therein, at any time with or without notice to you. We shall not be liable to you or any third party should we exercise such right. Modifications may include, but are not limited to, changes in the pricing structure, the addition of fee-based services, or changes to limitations on allowable file sizes. Any new features that augment or enhance the then current services on this site shall also be subject to these Terms of Use.
You understand and agree that temporary interruptions of the services available through this site may occur as normal events. You further understand and agree that we have has no control over third party networks you may access in the course of the use of this site, and therefore, delays and disruption of other network transmissions are completely beyond our control.
You understand and agree that the services available on this site are provided "AS IS" and that we assume no responsibility for the timeliness, deletion, loss or failure to store any user communications or personalization settings.
<br/><br/>
3. Registration Data and Privacy<br/>
In order to access some of the services on this site, you will require a separate account and password that can be obtained by completing our online registration form, which requests certain information and data ("Registration Data") and maintaining and updating your Registration Data as required. By registering, you agree that all information provided in the Registration Data is true and accurate and that you will maintain and update this information as required in order to keep it current, complete and accurate.
You also grant us the right to disclose to third parties certain Registration Data about you. The information we obtain through your use of this site, including your Registration Data, is subject to our Privacy Policy, which is specifically incorporated by reference into these Terms of Use.
<br/><br/>
4. Payment of Fees<br/>
If you subscribe to a service on this site that requires payment of a fee, you agree to pay all fees associated with such service. For all charges for services on this site, we will bill your debit card, credit card or bank account. Recurring charges are billed in advance of service. You agree to provide us with accurate and complete billing information, including valid credit card information, your name, address and telephone number, and to provide us with any changes in such information within thirty (30) days of the change.
If, for any reason, your credit card company or bank refuses to pay the amount billed for the service, you agree that we may, at our option, suspend or terminate your subscription to the service and require you to pay the overdue amount by other means acceptable to us. We may charge a fee for reinstatement of suspended or terminated accounts.
If, for any reason, the nonprofit or entity you designated to receive the funds refuses to accept the amount, you agree that we may, at our option, give those funds to another similar nonprofit or entity or set those funds aside in an account to be directed at a later time. There are no reimbursements for donations.
You agree that until your subscription to the service is terminated, you will continue to accrue charges for which you remain responsible, even if you do not use the service.
In the event legal action is necessary to collect on balances due, you agree to reimburse us for all expenses incurred to recover sums due, including attorney fees and other legal expenses.
<br/><br/>
5. Conduct on Site<br/>
Your use of the site is subject to all applicable laws and regulations, including Netiquette, and you are solely responsible for the contents of your communications through the site. By posting information in or otherwise using any communications service, chat room, message board, newsgroup, software library, or other interactive service that may be available to you on or through this site, you agree that you will not upload, share, post, or otherwise distribute or facilitate distribution of any content including text, communications, software, images, sounds, data, or other information that:
(a) Is unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another's privacy, tortuous, contains explicit or graphic descriptions or accounts of sexual acts (including but not limited to sexual language of a violent or threatening nature directed at another individual or group of individuals), or otherwise violates our rules or policies;
(b) Victimizes, harasses, degrades, or intimidates an individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age, or disability;
(c) Infringes on any patent, trademark, trade secret, copyright, right of publicity, or other proprietary right of any party;
(d) Constitutes unauthorized or unsolicited advertising, junk or bulk email (also known as "spamming"), chain letters, any other form of unauthorized solicitation, or any form of lottery or gambling;
(e) Contains software viruses or any other computer code, files, or programs that are designed or intended to disrupt, damage, or limit the functioning of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any data or other information of any third party; or
(f) Impersonates any person or entity, including any of our employees or representatives.
We neither endorse nor assume any liability for the contents of any material uploaded or submitted by third party users of the site. We generally do not prescreen, monitor, or edit the content posted by users of communications services, chat rooms, message boards, newsgroups, software libraries, or other interactive services that may be available on or through this site. However, we and our agents have the right at their sole discretion to remove any content that, in our judgment, does not comply with these Terms of Use and any other rules of user conduct for our site, or is otherwise harmful, objectionable, or inaccurate. We are not responsible for any failure or delay in removing such content. You hereby consent to such removal and waive any claim against us arising out of such removal of content. See "Use of Your Materials" below for a description of the procedures to be followed in the event that any party believes that content posted on this site infringes on any patent, trademark, trade secret, copyright, right of publicity, or other proprietary right of any party.
In addition, you may not use your account to breach security of another account or attempt to gain unauthorized access to another network or server. Not all areas of the site may be available to you or other authorized users of the site. You shall not interfere with anyone else's use and enjoyment of the site or other similar services. Users who violate systems or network security may incur criminal or civil liability.
You agree that we may at any time, and at our sole discretion, terminate your membership without prior notice to you for violating any of the above provisions. In addition, you acknowledge that we will cooperate fully with investigations of violations of systems or network security at other sites, including cooperating with law enforcement authorities in investigating suspected criminal violations.
<br/><br/>
6. Third Party Sites and Information<br/>
This site may link you to other sites on the Internet or otherwise include references to information, documents, software, materials and/or services provided by other parties. These sites may contain information or material that some people may find inappropriate or offensive. These other sites and parties are not under our control, and you acknowledge that we are not responsible for the accuracy, copyright compliance, legality, decency, or any other aspect of the content of such sites, nor are we responsible for errors or omissions in any references to other parties or their products and services. The inclusion of such a link or reference is provided merely as a convenience and does not imply endorsement of, or association with, the site or party by us, or any warranty of any kind, either expressed or implied.
SCHOOLD U (and/or any Affiliates) does/do not endorse, support, sanction, or verify the information or material on or accessible via the www.SCHOOLDU.com site. Unless otherwise specifically indicated, SCHOOLD U does not endorse and has no affiliation with any of the organizations mentioned, listed in, described on or linked to via the www.snoball.com site, and it makes no representations or warranties whatsoever with regard to those organizations or any other organization, entity or person.
<br/><br/>
7. Intellectual Property Information<br/>
Copyright  2013 SCHOOLD U All Rights Reserved.
For purposes of these Terms of Use, "content" is defined as any information, communications, software, photos, video, graphics, music, sounds, and other material and services that can be viewed by users on our site. This includes, but is in no way limited to, message boards, chat, and other original content.
By accepting these Terms of Use, you acknowledge and agree that all content presented to you on this site is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws, and is the sole property of SCHOOLD U and/or any Affiliates. You are only permitted to use the content as expressly authorized by us or the specific content provider. Except for a single copy made for personal use only, you may not copy, reproduce, modify, republish, upload, post, transmit, or distribute any documents or information from this site in any form or by any means without prior written permission from us or the specific content provider, and you are solely responsible for obtaining permission before reusing any copyrighted material that is available on this site. Any unauthorized use of the materials appearing on this site may violate copyright, trademark and other applicable laws and could result in criminal or civil penalties.
Neither we or our Affiliates warrant or represent that your use of materials displayed on, or obtained through, this site will not infringe the rights of third parties. See "Use of Your Materials" below for a description of the procedures to be followed in the event that any party believes that content posted on this site infringes on any patent, trademark, trade secret, copyright, right of publicity, or other proprietary right of any party.
All custom graphics, icons, logos and service names are registered trademarks, trademarks or service marks of SCHOOLD U and/or its Affiliates. All other trademarks or service marks are property of their respective owners. Nothing in these Terms of Use grants you any right to use any trademark, service mark, logo, and/or the name of SCHOOLD U and/or its Affiliates.
Certain of the ideas, software and processes incorporated into the service that is available on this site are protected by patent applications pending in the United States, and we intend to prepare and file additional patent applications in selected foreign jurisdictions.
<br/><br/>
8. User's Materials<br/>
Subject to our Privacy Policy, any communication or material that you transmit to this site or to us, whether by electronic mail or other means, for any reason, will be treated as non-confidential and nonproprietary. While you retain all rights in such communications or material, you grant us and our designated licensees a nonexclusive, paid-up, perpetual, and worldwide right to copy, distribute, display, perform, publish, translate, adapt, modify, and otherwise use such material for any purpose regardless of the form or medium (now known or not currently known) in which it is used.
Please do not submit confidential or proprietary information to us unless we have mutually agreed in writing otherwise. We are also unable to accept your unsolicited ideas or proposals, so please do not submit them to us in any circumstance.
We respect the intellectual property of others, and we ask you to do the same. If you or any user of this site believes its copyright, trademark or other property rights have been infringed by a posting on this site, you or the user should send notification to our Designated Agent (as identified below) immediately. To be effective, the notification must include:
(a) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed'
(b) Identification of the copyrighted work claimed to have been infringed;
(c) Information reasonably sufficient to permit us to contact the complaining party, such as address, telephone number and, if available, an electronic mail address at which the complaining party may be contacted;
(d) Identification of the material that is claimed to be infringing or to be subject to infringing activity and that is to be removed and information reasonably sufficient to permit us to locate the materials;
(e) A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, agent, or the law; and
(f) A statement that the information in the notification is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringing.
Pursuant to the Digital Millennium Copyright Act, 17 U.S.C. Sec. 512(c), our Designated Agent for Notice of claims of copyright infringement can be reached as indicated below. Service of repeat infringers of copyright or of users about whom repeat claims of copyright infringement are received will be terminated.
Designated Agent for Claimed Infringement:
SCHOOLD U<br/>
You acknowledge and agree that upon receipt of a notice of a claim of copyright infringement, we may immediately remove the identified materials from our site without liability to you or any other party and that the claims of the complaining party and the party that originally posted the materials will be referred to the United States Copyright Office for adjudication as provided in the Digital Millennium Copyright Act.
<br/><br/>
9. Disclaimer of Warranties<br/>
SCHOOLD U does not warrant or guarantee the accuracy, quality, completeness, currency, or validity of any information on the SCHOOLD U Web Site (including, without limitation, any database accessible via the www.SCHOOLDU.com site and its content) or linked from the www.SCHOOLDU.com site. The descriptive information is derived from IRS Forms 990, Forms 990-EZ, and Forms 990-PF filed by the nonprofit organizations or their voluntary responses to a Snoball questionnaire. The financial data are taken from the IRS Business Master File, IRS Forms 990, Forms 990-EZ, Forms 990-PF, FEC, or information provided to Snoball by organizations that are not required to file returns with the IRS. Snoball does not edit or control the financial information received, although it may (in its sole discretion) note obvious mathematical errors that it believes may exist in the materials as received by it.
Due to, among other things, the possibility of human and/or mechanical error, Snoball and SCHOOLD U shall not be responsible for any errors or omissions on the www.SCHOOLDU.com site. Snoball and SCHOOLD U make no representations as to the accuracy or integrity of the information contained therein, including, without limitation, any content thereon. Snoball and SCHOOLD U shall not be liable for any damages of any kind incurred as a result of the information posted on the www.snoball.com site including, without limitation, any content thereon.
ALL MATERIALS AND SERVICES ON THIS SITE ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR THE WARRANTY OF NONINFRINGEMENT. WITHOUT LIMITING THE FOREGOING, WE MAKE NO WARRANTY THAT (a) THE SERVICES AND MATERIALS WILL MEET YOUR REQUIREMENTS, (b) THE SERVICES AND MATERIALS WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERRORFREE,  THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES OR MATERIALS WILL BE EFFECTIVE, ACCURATE OR RELIABLE, OR (d) THE QUALITY OF ANY PRODUCTS, SERVICES, OR INFORMATION PURCHASED OR OBTAINED BY YOU FROM THE SITE FROM US OR OUR AFFILIATES WILL MEET YOUR EXPECTATIONS OR BE FREE FROM MISTAKES, ERRORS OR DEFECTS.
THIS SITE COULD INCLUDE TECHNICAL OR OTHER MISTAKES, INACCURACIES OR TYPOGRAPHICAL ERRORS. WE MAY MAKE CHANGES TO THE MATERIALS AND SERVICES AT THIS SITE, INCLUDING THE PRICES AND DESCRIPTIONS OF ANY PRODUCTS LISTED HEREIN, AT ANY TIME WITHOUT NOTICE. THE MATERIALS OR SERVICES AT THIS SITE MAY BE OUT OF DATE, AND WE MAKE NO COMMITMENT TO UPDATE SUCH MATERIALS OR SERVICES.
THE USE OF THE SERVICES OR THE DOWNLOADING OR OTHER ACQUISITION OF ANY MATERIALS THROUGH THIS SITE IS DONE AT YOUR OWN DISCRETION AND RISK AND WITH
YOUR AGREEMENT THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM SUCH ACTIVITIES.
Through your use of the site, you may have the opportunities to engage in commercial transactions with other users and vendors. You acknowledge that all transactions relating to any merchandise or services offered by any party, including, but not limited to the purchase terms, payment terms, warranties, guarantees, maintenance and delivery terms relating to such transactions, are agreed to solely between the seller or purchaser of such merchandise and services and you. 
WE MAKE NO WARRANTY REGARDING ANY TRANSACTIONS EXECUTED THROUGH, OR IN CONNECTION WITH THIS SITE, AND YOU UNDERSTAND AND AGREE THAT SUCH TRANSACTIONS ARE CONDUCTED ENTIRELY AT YOUR OWN RISK. ANY WARRANTY THAT IS PROVIDED IN CONNECTION WITH ANY PRODUCTS, SERVICES, MATERIALS, OR INFORMATION AVAILABLE ON OR THROUGH THIS SITE FROM A THIRD PARTY IS PROVIDED SOLELY BY SUCH THIRD PARTY, AND NOT BY US OR ANY OTHER OF OUR AFFILIATES.
Content available through this site often represents the opinions and judgments of an information provider, site user, or other person or entity not connected with SCHOOLD U. We do not endorse, nor are we responsible for the accuracy or reliability of, any opinion, advice, or statement made by anyone other than an authorized SCHOOLD U spokesperson speaking in his/her official capacity. Please refer to the specific editorial policies posted on various sections of this site for further information, which policies are incorporated by reference into these Terms of Use.
In addition, the materials on this site may include sample or form agreements, letters or other documents, including financially or legally significant documents such as contracts and other items ("Forms"). These Forms are provided solely as examples of typical documents of their kind, and the delivery and use of Forms does not constitute legal, accounting or other professional advice. Under no circumstances will SCHOOLD U or its Affiliates be liable for any loss or damages caused by your reliance on information or advice obtained through this site, including your use of any of the Forms. It is your responsibility to evaluate the accuracy, completeness, or usefulness of any information, opinions, advice, Forms or other content available on or through this site. In particular, you are urged to consult an appropriate professional licensed in your jurisdiction before using any Forms or otherwise relying on any legal, accounting, or other professional advice or information obtained on or through this site.
SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES, SO SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.
<br/><br/>
10. Limitation of Liability<br/>
Your exclusive remedy and our entire liability, if any, for any claims arising out of these Terms of Use and your use of this site shall be limited to the amount you donated through the site during the twelve (12) month period before the act giving rise to the liability.
IN NO EVENT SHALL WE OR OUR AFFILIATES BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY SPECIAL, PUNITIVE, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, THOSE RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER OR NOT WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND ON ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE USE OF THIS SITE OR OF ANY WEB SITE REFERENCED OR LINKED TO FROM THIS SITE.
FURTHER, WE SHALL NOT BE LIABLE IN ANY WAY FOR THIRD PARTY GOODS AND SERVICES OFFERED THROUGH THIS SITE OR FOR ASSISTANCE IN CONDUCTING COMMERCIAL TRANSACTIONS THROUGH THIS SITE, INCLUDING WITHOUT LIMITATION THE PROCESSING OF DONATIONS.
SOME JURISDICTIONS PROHIBIT THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.
<br/><br/>
11. Indemnification<br/>
Upon a request by us, you agree to defend, indemnify, and hold us and our Affiliates harmless from all liabilities, claims, and expenses, including attorney's fees that arise from your use or misuse of this site. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will cooperate with us in asserting any available defenses.
<br/><br/>
12. Participation in Promotions<br/>
From time to time, this site may include advertisements offered by third parties. You may enter into correspondence with or participate in promotions of the advertisers showing their products on this site. Any such correspondence or promotions, including the delivery of and the payment for goods and services, and any other terms, conditions, warranties or representations associated with such correspondence or promotions, are solely between you and the advertiser. We assume no liability, obligation or responsibility for any part of any such correspondence or promotion.
<br/><br/>
13. Use of Site and Storage of Material<br/>
You acknowledge that we may establish general practices and limits concerning use of the services available on our site, including without limitation the maximum number of days that uploaded content will be retained on the site, the maximum disk space that will be allotted or our servers on your behalf, and the maximum number of times (and the maximum duration for which) you may access the services in a given period of time. You agree that we have no responsibility or liability for the deletion or failure to store any content maintained or transmitted on or through this site. You acknowledge that we reserve the right to log off accounts which have not paid a subscription fee or that are inactive for an extended period of time. You further acknowledge that we reserve the right to change these general practices and limits at any time, in our sole discretion, with or without notice.
We provide storage space and access for material through our site. For purposes of these Terms of Use, "material" refers to all forms of communication that we may allow, including narrative descriptions, graphics (including photographs, illustrations, images, drawings, logos), executable programs, video recordings, and audio recordings. You may not use this site to publish material that we determine, at our sole discretion, to be unlawful, indecent, or objectionable, or which violates the restrictions described in "Your Conduct on the Site" above. We will not routinely monitor the contents of your online portfolio. You are solely responsible for any information contained in your online portfolios. However, if complaints are received regarding language, content, or graphics contained in your online portfolio, we may, at our sole discretion, remove the images hosted on our servers and terminate your Web hosting service. We may also suspend the account, restrict access to it, or remove content from it if necessary or appropriate.
The accounts of our users operate on shared resources. Excessive use or abuse of these shared network resources by one user may have a negative impact on all other users. Misuse of network resources in a manner that impairs network performance, including excessive consumption of CPU time, memory, disk space, and session time, is prohibited and may result in termination of your account or limitation of your activities.
This site is not designed or intended to be used as a disaster recovery facility or as an emergency data storage facility. Although we take reasonable precautions to preserve and protect the material you upload to the site, you should not rely on the site as your only storage facility. You should preserve backup copies of any digital data, information or other materials that you have uploaded. You agree not to hold us for any damage to, any deletion of or any failure to store your files, data or Registration Data.
<br/><br/>
14. Security and Password<br/>
You are solely responsible for maintaining the confidentiality of your password and account and for any and all statements made and acts or omissions that occur through the use of your password and account, including any mail sent and any charges incurred. Therefore, you must take steps to ensure that others do not gain access to your password and account. Our personnel will never ask you for your password. You may not transfer or share your account with anyone, and we reserve the right to immediately terminate your account in the event of any unauthorized transfer or sharing thereof.
<br/><br/>
15. Export Controls<br/>
Software available on or through this site is subject to United States Export Controls. No software from this site may be downloaded or exported (a) into (or to a resident of) Cuba, Iraq, Libya, North Korea, Iran, Syria, or any other country which the United States has embargoed goods; or (b) anyone on the United States Treasury Department's list of Specially Designated Nationals or the United States Commerce Department's Table of Deny Orders. By downloading or using the software, you represent and warrant that you are not located in, under the control of, or a national or resident of any such country or on any such list.
<br/><br/>
16. International Use<br/>
Although this site may be accessible worldwide, we make no representation that materials on this site are appropriate or available for use in locations outside the United States, and accessing them from territories where their contents are illegal is prohibited. Those who choose to access this site from other locations do so on their own initiative and are responsible for compliance with local laws. Any offer for any product, service, and/or information made in connection with this site is void where prohibited.
<br/><br/>
17. Termination of Use<br/>
You agree that we may, in our sole discretion, terminate or suspend your access to all or part of the site with or without notice and for any reason, including, without limitation, breach of these Terms of Use. Any suspected fraudulent, abusive or illegal activity may be grounds for terminating your relationship and may be referred to appropriate law enforcement authorities.
Upon termination or suspension, regardless of the reasons therefore, your right to use the services available on this site immediately ceases, and you acknowledge and agree that we may immediately deactivate or delete your account and all related information and files in your account and/or bar any further access to such files or this site. We shall not be liable to you or any third party for any claims or damages arising out of any termination or suspension or any other actions taken by us in connection therewith. Sections 1, 3, 511, 14, and 1719 of these Terms of Use, as well as your liability for any unpaid fees, shall survive any termination.
<br/><br/>
18. Governing Law<br/>
This site (excluding any linked sites) is controlled by us from our offices within the State of Texas, United States of America. It can be accessed from all 50 states, as well as from other countries around the world. As each of these places has laws that may differ from those of Texas, by accessing this site both of us agree that the statutes and laws of the State of Texas, without regard to the conflicts of laws principles thereof and the United Nations Convention on the International Sales of Goods, will apply to all matters relating to the use of this site and the purchase of products and services available through this site. Each of us agrees and hereby submits to the exclusive personal jurisdiction and venue of the courts of Travis County, Texas and/or the United States District Court for the Southern District of Texas with respect to such matters.
<br/><br/>
19. Notices<br/>
All notices to a party shall be in writing and shall be made by conventional mail. Notices to us must be sent to the attention of Customer Service at SCHOOLD U. Notices to you may be sent either to the e-mail address supplied for your account or to the address supplied by you as part of your Registration Data. In addition, we may broadcast notices or messages through the site to inform you of changes to the site or other matters of importance, and such broadcasts shall constitute notice to you.
Any notices or communication under these Terms of Use will be deemed delivered to the party receiving such communication (a) on the delivery date if delivered personally to the party; (b) two business days after deposit with a commercial overnight carrier, with written verification of receipt; (c) five business days after the mailing date, if sent by US mail, return receipt requested; (d) on the delivery date if transmitted by confirmed facsimile; or (e) on the delivery date if transmitted by confirmed e-mail.
<br/><br/>
20. Entire Agreement<br/>
These terms and conditions constitute the entire agreement and understanding between us concerning the subject matter hereof and supersedes all prior agreements and understandings of the parties with respect thereto. These Terms of Use may NOT be altered, supplemented, or amended by the use of any other document(s). Any attempt to alter, supplement or amend this document or to enter an order for products or services which are subject to additional or altered terms and conditions shall be null and void, unless otherwise agreed to in a written agreement signed by you and us. To the extent that anything in or associated with this site is in conflict or inconsistent with these Terms of Use, these Terms of Use shall take precedence.
<br/><br/>
21. Miscellaneous<br/>
In any action to enforce these Terms of Use, the prevailing party will be entitled to costs and attorneys' fees. Any cause of action brought by you against us or our Affiliates must be instituted with one year after the cause of action arises or be deemed forever waived and barred.
You may not assign your rights and obligations under these Terms of Use to any third party, and any purported attempt to do so shall be null and void. We may free assign our rights and obligations under these Terms of Use.
You agree not to sell, resell, reproduce, duplicate, copy or use for any commercial purposes any portion of this site, or use of or access to this site.
In addition to any excuse provided by applicable law, we shall be excused from liability for non-delivery or delay in delivery of charitable donations and services available through our site arising from any event beyond our reasonable control, whether or not foreseeable by either party, including but not limited to, labor disturbance, war, fire, accident, adverse weather, inability to secure transportation, governmental act or regulation, and other causes or events beyond our reasonable control, whether or not similar to those which are enumerated above.
If any part of these Terms of Use is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of the parties, and the remaining portions shall remain in full force and effect.
Any failure by us to enforce or exercise any provision of these Terms of Use or related rights shall not constitute a waiver of that right or provision.
<br/><br/>
22. Contact Information<br/>
Except as explicitly noted on this site, the services available through this site are offered by SCHOOLD U. If you are a Texas resident, you may have this same information e-mailed to you by sending a letter to the foregoing address with your e- mail address and a request for this information. If you notice that any user is violating these Terms of Use, please contact us: support@schooldu.com
</div>
